import { Fragment } from 'react'
import type { NextPage } from 'next'
import {FeaturedPosts, Hero} from '../components/homePage'
import Head from 'next/head'


const HomePage: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Full Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <FeaturedPosts />
    </Fragment>
  )
}

export default HomePage
